{{- range .Values.monitoredClusters }}
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: stack-monitoring
spec:
  version: {{ $.Values.version }}
  # Enable remote cluster server so the monitoring cluster can run CCS against this cluster.
  # See: https://www.elastic.co/docs/deploy-manage/remote-clusters/eck-remote-clusters
  remoteClusterServer:
    enabled: true
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: {{ $.Values.monitoringCluster.elasticsearchName }}
          namespace: {{ $.Values.monitoringCluster.namespace }}
    logs:
      elasticsearchRefs:
        - name: {{ $.Values.monitoringCluster.elasticsearchName }}
          namespace: {{ $.Values.monitoringCluster.namespace }}
  {{- if $.Values.enforceRBAC }}
  # Required when operator runs with --enforce-rbac-on-refs (cross-namespace ref to monitoring ES).
  serviceAccountName: {{ .Values.monitoringCluster.serviceAccountName }}
  {{- end }}
  nodeSets:
    - name: default
      count: {{ .nodeCount }}
      config:
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ $.Values.storageSize }}
{{- end }}