{{- if .Values.enforceRBAC }}
{{- range .Values.monitoredClusters }}
# ServiceAccount in monitored namespace; RoleBinding in monitoring namespace allows it to GET monitoring Elasticsearch.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.crossNamespaceServiceAccountName }}
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: stack-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-{{ .name }}-from-remote-namespace
  namespace: {{ $.Values.monitoringCluster.namespace }}
  labels:
    app.kubernetes.io/name: stack-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elasticsearch-association
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.crossNamespaceServiceAccountName }}
    namespace: {{ .namespace }}
{{- end }}
{{- end }}