{{- if .Values.enforceRBAC }}
{{- if .Values.monitoringCluster }}
{{- $monitoringSA := (.Values.monitoringCluster.serviceAccountName) | default "eck-monitoring-sa" }}
{{- $monitoredSA := (.Values.monitoringCluster.monitoredServiceAccountName) | default "eck-monitored-sa" }}
# ---
# Two ServiceAccounts: one for the monitoring cluster, one for monitored clusters.
# RoleBindings: monitoring SA can access each monitored cluster; each monitored SA can access the monitoring cluster.
# ---
# 1) ServiceAccount for the monitoring cluster (used by monitoring ES to access elastic1/elastic2 via remoteClusters).
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $monitoringSA }}
  namespace: {{ .Values.monitoringCluster.namespace }}
  labels:
    app.kubernetes.io/name: stack-monitoring
---
# 2) ServiceAccount for each monitored cluster (used by monitored ES to access the monitoring cluster for stack monitoring).
{{- range .Values.monitoredClusters }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $monitoredSA }}
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: stack-monitoring
{{- end }}
# 3) RoleBinding per monitored cluster: allow the MONITORING ServiceAccount to access Elasticsearch in that monitored namespace (elasticsearch-association).
{{- range .Values.monitoredClusters }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-monitoring-cluster-from-remote-namespace
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: stack-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elasticsearch-association
subjects:
  - kind: ServiceAccount
    name: {{ $monitoringSA }}
    namespace: {{ $.Values.monitoringCluster.namespace }}
{{- end }}
# 4) RoleBinding per monitored cluster in the MONITORING namespace: allow that MONITORED ServiceAccount to access the monitoring Elasticsearch.
{{- range .Values.monitoredClusters }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-{{ .name }}-from-remote-namespace
  namespace: {{ $.Values.monitoringCluster.namespace }}
  labels:
    app.kubernetes.io/name: stack-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elasticsearch-association
subjects:
  - kind: ServiceAccount
    name: {{ $monitoredSA }}
    namespace: {{ .namespace }}
{{- end }}
{{- end }}
{{- end }}
