{{- if .Values.enforceRBAC }}
# ServiceAccount in monitoring namespace (for use by resources in elastic-monitoring if needed).
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.monitoringCluster.serviceAccountName | default "eck-monitoring-sa" }}
  namespace: {{ .Values.monitoringCluster.namespace }}
  labels:
    app.kubernetes.io/name: stack-monitoring
{{- range .Values.monitoredClusters }}
# RoleBinding in monitoring namespace: allows default ServiceAccount from monitored namespace to GET monitoring Elasticsearch.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-{{ .name }}-from-remote-namespace
  namespace: {{ $.Values.monitoringCluster.namespace }}
  labels:
    app.kubernetes.io/name: stack-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elasticsearch-association
subjects:
  - kind: ServiceAccount
    name: {{ .Values.monitoringCluster.serviceAccountName | default "eck-monitoring-sa" }}
    namespace: {{ .Values.monitoringCluster.namespace }}
{{- end }}
{{- end }}