{{- if .Values.enforceRBAC }}
{{- if .Values.monitoringCluster }}
# ServiceAccount in monitoring namespace (for use by resources in elastic-monitoring if needed).
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ (.Values.monitoringCluster.serviceAccountName) | default "eck-monitoring-sa" }}
  namespace: {{ .Values.monitoringCluster.namespace }}
  labels:
    app.kubernetes.io/name: stack-monitoring
---
# RoleBinding so the monitoring namespace ServiceAccount can GET Elasticsearch in this namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-monitoring-sa-elasticsearch-association
  namespace: {{ .Values.monitoringCluster.namespace }}
  labels:
    app.kubernetes.io/name: stack-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elasticsearch-association
subjects:
  - kind: ServiceAccount
    name: {{ (.Values.monitoringCluster.serviceAccountName) | default "eck-monitoring-sa" }}
    namespace: {{ .Values.monitoringCluster.namespace }}
---
{{- end }}
{{- if .Values.monitoringCluster }}
{{- range .Values.monitoredClusters }}
# ServiceAccount in monitored namespace: same name as in monitoring cluster, used by ES pods for cross-namespace association.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.monitoredClusters.serviceAccountName }}
  namespace: {{ $.Values.monitoredClusters.namespace }}
  labels:
    app.kubernetes.io/name: stack-monitoring
---
# RoleBinding in monitoring namespace: allows this ServiceAccount from monitored namespace to GET monitoring Elasticsearch.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-{{ .name }}-from-remote-namespace
  namespace: {{ $.Values.monitoringCluster.namespace }}
  labels:
    app.kubernetes.io/name: stack-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elasticsearch-association
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.monitoredClusters.serviceAccountName }}
    namespace: {{ $.Values.monitoredClusters.namespace }}
{{- end }}
{{- end }}
{{- end }}